src/CoreBundle/Entity/Lobby.php
<?php

namespace CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\User;

/**
 * Lobby
 *
 * @ORM\Table(name="lobby")
 * @ORM\Entity(repositoryClass="CoreBundle\Repository\LobbyRepository")
 */
class Lobby
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="PlayerNumber", type="smallint")
     */
    private $playerNumber;
    
    /**
     * @var string
     *
     * @ORM\Column(name="hostName", type="string")
     */
    private $hostUsername;
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="UserBundle\Entity\User", mappedBy="lobby", cascade={"persist", "refresh"})
     */
    private $users;
    
    /**
     * @var int
     * 
     * @ORM\Column(name="HistorySize", type="smallint")
     */
    private $historySize;
    
    /**
     * @var int
     * 
     * @ORM\Column(name="GameBegin", type="smallint", nullable=true)
     */
    private $gameId;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set playerNumber
     *
     * @param integer $playerNumber
     *
     * @return Lobby
     */
    public function setPlayerNumber($playerNumber)
    {
        $this->playerNumber = $playerNumber;
        $this->historySize++;
        return $this;
    }

    /**
     * Get playerNumber
     *
     * @return int
     */
    public function getPlayerNumber()
    {
        return $this->playerNumber;
    }
    
    /**
     * Set hostUsername
     *
     * @param string $hostUsername
     *
     * @return Lobby
     */
    public function setHostUsername($hostUsername)
    {
        $this->hostUsername = $hostUsername;
        
        return $this;
    }
    
    /**
     * Get hostUsername
     *
     * @return string
     */
    public function getHostUsername()
    {
        return $this->hostUsername;
    }

    /**
     * Add user
     *
     * @param \UserBundle\Entity\User $user
     *
     * @return Lobby
     */
    public function addUser(\UserBundle\Entity\User $user)
    {
        $this->users[] = $user;
        $user->setLobby($this);
        $this->historySize++;

        return $this;
    }

    /**
     * Remove user
     *
     * @param \UserBundle\Entity\User $user
     */
    public function removeUser(\UserBundle\Entity\User $user)
    {
        $this->users->removeElement($user);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUsers()
    {
        return $this->users;
    }
    
    /**
     * Set historySize
     *
     * @param integer $historySize
     *
     * @return Lobby
     */
    public function setHistorySize($historySize)
    {
        $this->historySize = $historySize;
        
        return $this;
    }
    
    /**
     * Get historySize
     *
     * @return integer
     */
    public function getHistorySize()
    {
        return $this->historySize;
    }
    
    /**
     * Set gameId
     *
     * @param integer $gameId
     *
     * @return Lobby
     */
    public function setGameId($gameId)
    {
        $this->gameId = $gameId;
        $this->historySize++;
        
        return $this;
    }
    
    /**
     * Get gameId
     *
     * @return integer
     */
    public function getGameId()
    {
        return $this->gameId;
    }
    
    public function  __construct()
    {
        $this->playerNumber = 2;
        $this->historySize = 0;
        $this->gameBegin = false;
    }
    
    public function getWaitingUsers()
    {
        return $this->playerNumber - $this->users->count();
    }
    
    public function addPlayerNumber()
    {
        if($this->playerNumber < 4) {
            $this->playerNumber++;
            $this->historySize++;
        }
    }
    
    public function removePlayerNumber()
    {
        if($this->playerNumber > 2) {
            $this->playerNumber--;
            $this->historySize++;
        }
    }
    
    /**
     * 
     * @param \UserBundle\Entity\User $user
     * @return boolean true si l'utilisateur est déjà dans le lobby
     */
    public function isUserInLobby(\UserBundle\Entity\User $user)
    {
        return $this->users->contains($user);
    }
}

src/CoreBundle/Controller/LobbyController.php
<?php

namespace CoreBundle\Controller;

use CoreBundle\Entity\Lobby;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class LobbyController extends Controller
{
    /**
     * @Route("/lobby/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function lobbyAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->getLobbyWithUsers($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        return $this->render('CoreBundle:Lobby:lobby.html.twig', [
            'lobby' => $lobby
        ]);
    }
    
    /**
     * @Route("/lobby/create/{nb}", requirements={"nb": "[2-4]"})
     */
    public function createLobbyAction($nb)
    {
        $em = $this->getDoctrine()->getManager();
        
        if ($this->getUser()->getPlayer() != null) {
            throw new NotFoundHttpException("Vous avez une partie en cours");
        }
        
        $lobby = new Lobby();
        $lobby->setPlayerNumber($nb);
        $lobby->addUser($this->getUser());
        $lobby->setHostUsername($this->getUser()->getUsername());
        $em->persist($lobby);
        $em->flush();
        
        return $this->redirectToRoute('core_lobby_lobby', array(
            'lobbyId' => $lobby->getId()
        ));
    }
    
    /**
     * @Route("/lobby/delete/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function deleteLobbyAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->getLobbyWithUsers($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        if ( $lobby->getHostUsername() != $this->getUser()->getUsername() ) {
            throw new NotFoundHttpException("Vous ne possedez pas ce lobby.");
        } else {
            $em = $this->getDoctrine()->getManager();
            foreach ($lobby->getUsers() as $user) {
                $user->setLobby(null);
            }
            $em->remove($lobby);
            $em->flush();
        }
        
        return $this->redirectToRoute('core_index_index');
        
    }
    
    /**
     * @Route("/lobby/addUser/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function addUserAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->getLobbyWithUsers($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        if ($this->getUser()->getPlayer() != null) {
            throw new NotFoundHttpException("Vous avez une partie en cours");
        }
        
        /* Test si le joueur est déjà dans le lobby */
        if( $lobby->isUserInLobby($this->getUser()) === false ) {
            $em = $this->getDoctrine()->getManager();
            $lobby->addUser($this->getUser());
            $em->flush();
        }
        
        return $this->redirectToRoute('core_lobby_lobby', array(
            'lobbyId' => $lobby->getId()
        ));
        
    }
    
    /**
     * 
     * @Route("/lobby/addPlayerNumber/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function addPlayerAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->getLobbyWithUsers($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        if ( $lobby->getHostUsername() != $this->getUser()->getUsername() ) {
            throw new NotFoundHttpException("Vous ne possedez pas ce lobby.");
        } else {
            $em = $this->getDoctrine()->getManager();
            $lobby->addPlayerNumber();
            $em->flush();
        }
        
        return $this->redirectToRoute('core_lobby_lobby', array(
            'lobbyId' => $lobby->getId()
        ));
    }
    
    /**
     *
     * @Route("/lobby/removePlayerNumber/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function removePlayerAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->getLobbyWithUsers($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        if ( $lobby->getHostUsername() != $this->getUser()->getUsername() ) {
            throw new NotFoundHttpException("Vous ne possedez pas ce lobby.");
        } else {
            $em = $this->getDoctrine()->getManager();
            $lobby->removePlayerNumber();
            $em->flush();
        }
        
        return $this->redirectToRoute('core_lobby_lobby', array(
            'lobbyId' => $lobby->getId()
        ));
    }
    
    /**
     * @Route("/lobby/update/{lobbyId}", requirements={"lobbyId": "\d+"})
     */
    public function updateAction($lobbyId)
    {
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('CoreBundle:Lobby')
        ;
        
        $lobby = $repository->find($lobbyId);
        
        if (null === $lobby) {
            throw new NotFoundHttpException("Le lobby ".$lobbyId." n'existe pas.");
        }
        
        return new JsonResponse(array(
            'historySize' => $lobby->getHistorySize(),
            'gameId' => $lobby->getGameId()
        ));
    }
}

src/CoreBundle/Resources/views/Lobby/lobby.html.twig
{% extends 'CoreBundle:Parts:base.html.twig' %}
{% block title %}Lobby - {{ parent() }}{% endblock %}

{% block nav %}
{% include 'CoreBundle:Parts:nav.html.twig' %}
{% endblock %}

{% block body %}
<div class="container">
	<h1>Lobby {{ lobby.id }}</h1>
	{% if lobby.gameId == null %}
        	<p>Hôte : {{ lobby.hostUsername }}</p>
        	<h3>Liste des joueurs</h3>
        	
        	<ul>
        	{% for user in lobby.users %}
        		<li>{{ user.username }}</li>	
        	{% endfor %}
        	</ul>
        	<p>{{ lobby.waitingUsers }} joueur en attente.
        	{% if app.user.username == lobby.hostUsername %}
        	    {% if lobby.playerNumber < 4 %}
        		<a class="btn waves-effect waves-light blue lighten-2" href="{{ path('core_lobby_addplayer', {'lobbyId' : lobby.id}) }}">
        			Ajouter un joueur<i class="material-icons right">add</i></a>
        	    {% endif %}
        	    {% if lobby.playerNumber > 2 %}
        			<a class="btn waves-effect waves-light red" href="{{ path('core_lobby_removeplayer', {'lobbyId' : lobby.id}) }}">
        			Retirer un joueur<i class="material-icons right">remove</i></a>
        	    {% endif %}
        		</p>
        		<a class="btn waves-effect waves-light pink darken-3" href="{{ path('core_lobby_deletelobby', {'lobbyId' : lobby.id}) }}">
        			Supprimer le lobby<i class="material-icons right">delete</i></a>
        		<a class="btn waves-effect waves-light {% if lobby.waitingUsers > 0 %}disabled{% endif %}" href="{{ path('loveletter_default_newgame', {'lobbyId' : lobby.id}) }}">
        			Lancer la partie<i class="material-icons right">send</i></a>
        	{% endif %}
	{% else %}
        	<a class="btn waves-effect waves-light" href="{{ path('loveletter_default_view', {'id' : lobby.gameId}) }}">
        			Rejoindre la partie<i class="material-icons right">send</i></a>
	{% endif %}
</div>

{% endblock %}

{% block footer %}
{% include 'CoreBundle:Parts:footer.html.twig' %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script type="text/javascript">

	var historySize = {{ lobby.HistorySize }};
	var x = setInterval(function() {
		
        $.ajax({
            url: '{{ path('core_lobby_update', {'lobbyId': lobby.id}) }}',
            dataType: 'json',
            success: function( data ) {
        			if(data['gameId'] != null)
        				window.location.href = "../../game/view/"+data['gameId'];
        			else if(data['historySize'] != historySize) {
        				window.location.href = "{{ path('core_lobby_lobby', {'lobbyId': lobby.id}) }}";
        		}},
            error: function( data ) {
            		window.location.href = "{{ path('core_index_index') }}";
            }
          });
	}, 5000);
	</script>
{% endblock %}